In [2]:
# Import Pandas
import pandas as pd

In [3]:
# Create a Dataframe with the world emission data
df = pd.read_csv("./data/owid-co2-data.csv")

# Fill the blank data with 0 since all blanks are numbers
df = df.fillna(0)
df.head()

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
0,Afghanistan,1850,AFG,3752993.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Afghanistan,1851,AFG,3767956.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.165,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Afghanistan,1852,AFG,3783940.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.164,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,1853,AFG,3800954.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.164,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,1854,AFG,3818038.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.163,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
# Make a dataframe with only data from 1970 to the most current year
# Clear remaining NAN and reset the index
df = df.where(df["year"] >= 1970, axis=0).dropna().reset_index(drop=True)
df

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
0,Afghanistan,1970.0,AFG,10752973.0,1.581223e+10,0.047,0.004,1.670,0.729,77.469,...,0.0,0.123,0.000,0.000,0.001,0.0,0.00,0.00,0.000,0.000
1,Afghanistan,1971.0,AFG,11015853.0,1.577051e+10,0.043,0.004,1.894,0.223,13.360,...,0.0,0.122,0.000,0.000,0.001,0.0,0.00,0.00,0.000,0.000
2,Afghanistan,1972.0,AFG,11286753.0,1.317055e+10,0.046,0.004,1.530,-0.363,-19.181,...,0.0,0.120,0.000,0.000,0.001,0.0,0.00,0.00,0.000,0.000
3,Afghanistan,1973.0,AFG,11575308.0,1.356863e+10,0.067,0.006,1.635,0.105,6.868,...,0.0,0.119,0.000,0.000,0.001,0.0,0.00,0.00,0.000,0.000
4,Afghanistan,1974.0,AFG,11869881.0,1.430911e+10,0.070,0.006,1.913,0.278,16.980,...,0.0,0.118,0.000,0.000,0.001,0.0,0.00,0.00,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13735,Zimbabwe,2018.0,ZWE,15052191.0,2.271535e+10,0.558,0.037,10.715,1.419,15.265,...,0.0,0.114,0.001,0.001,0.002,0.0,116.76,29.37,-0.088,-0.825
13736,Zimbabwe,2019.0,ZWE,15354606.0,0.000000e+00,0.473,0.031,9.775,-0.939,-8.765,...,0.0,0.113,0.001,0.001,0.002,0.0,116.03,28.70,0.143,1.463
13737,Zimbabwe,2020.0,ZWE,15669663.0,0.000000e+00,0.496,0.032,7.850,-1.926,-19.700,...,0.0,0.112,0.001,0.001,0.002,0.0,113.20,25.99,0.818,10.421
13738,Zimbabwe,2021.0,ZWE,15993525.0,0.000000e+00,0.531,0.033,8.396,0.547,6.962,...,0.0,0.111,0.001,0.001,0.002,0.0,0.00,0.00,1.088,12.956
13739,Zimbabwe,2022.0,ZWE,16320539.0,0.000000e+00,0.531,0.033,8.856,0.460,5.477,...,0.0,0.000,0.000,0.000,0.000,0.0,0.00,0.00,0.000,0.000

In [6]:
# Write the clean data to a new csv file
df.to_csv("World Emission Data.csv")